name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: true

  test:
    name: npm ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ["test"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Configure
        run: |
          git config --global user.email uirouter@github.actions
          git config --global user.name uirouter_github_actions
      - name: Install Dependencies
        run: npm ci
      # - name: Check Peer Dependencies
      #   run: npx check-peer-dependencies
      - name: Run Tests
        run: npm run ${{ matrix.script }}
